In [1]:
import pandas as pd
import os

reports_path = "../../generated/reports-no-bug"
code_analysis_generated_path = "../../generated/code-analysis"

if not os.path.exists(code_analysis_generated_path):
    os.makedirs(code_analysis_generated_path)

data = []

users = os.listdir(reports_path)
for user in users:
    uploads_path = os.path.join(reports_path, user)

    pitest_path = os.path.join(uploads_path, "Pitest", "mutations.xml")
    pitest_valid = os.path.exists(pitest_path)

    data.append([user, pitest_path, pitest_valid])


main_df = pd.DataFrame(data, columns=['user', 'pitest', 'pitest_valid'])

main_df

,user,pitest,pitest_valid
0,0947a22a-ec40-4f49-867b-330a623a1a35,../../generated/reports-no-bug\0947a22a-ec40-4...,True
1,0d271530-be17-4538-bf04-dde3c6069b5f,../../generated/reports-no-bug\0d271530-be17-4...,True
2,11555248-3f01-4d1c-9a71-ef7caf9150fa,../../generated/reports-no-bug\11555248-3f01-4...,False
3,70c71a91-06a1-4bf4-8e56-f4327b1c8b3f,../../generated/reports-no-bug\70c71a91-06a1-4...,True
4,70e85b5e-92d4-498a-9079-ba881f5b3b82,../../generated/reports-no-bug\70e85b5e-92d4-4...,True
5,7234f6dc-a316-4576-8453-6e10d7cf1c3d,../../generated/reports-no-bug\7234f6dc-a316-4...,True
6,84c2c4e6-1c27-4f2c-808b-9e84a7cb257e,../../generated/reports-no-bug\84c2c4e6-1c27-4...,True
7,960ad9f8-2b83-4526-9cfb-1a59cec049a6,../../generated/reports-no-bug\960ad9f8-2b83-4...,False
8,bcec21aa-2246-4ee8-9f2a-3998a5cde697,../../generated/reports-no-bug\bcec21aa-2246-4...,True
9,c27240eb-52c0-4436-aa0f-e7f97a94a725,../../generated/reports-no-bug\c27240eb-52c0-4...,True
10,c44fb8ae-6e48-4f56-b5ea-1727c487a5e7,../../generated/reports-no-bug\c44fb8ae-6e48-4...,True
11,eda1acdb-c4bb-4425-a39f-4c25a998e739,../../generated/reports-no-bug\eda1acdb-c4bb-4...,True
12,fb270a09-6a45-4eae-8f9a-3c808faec3ee,../../generated/reports-no-bug\fb270a09-6a45-4...,True

# Add group

In [2]:
users_csv_path = '../../generated/database/users.csv'
if not os.path.exists(users_csv_path):
    raise FileNotFoundError(f"Le fichier {users_csv_path} n'existe pas. Exécutez le notebook 'notebooks/arrange data/Database data.ipynb' pour le générer.")

df_users = pd.read_csv(users_csv_path, usecols=['user', 'game_mode'])
main_df = main_df.merge(df_users, on=['user'], how='left').dropna()
main_df

,user,pitest,pitest_valid,game_mode
0,0947a22a-ec40-4f49-867b-330a623a1a35,../../generated/reports-no-bug\0947a22a-ec40-4...,True,TEAM
1,0d271530-be17-4538-bf04-dde3c6069b5f,../../generated/reports-no-bug\0d271530-be17-4...,True,SOLO
2,11555248-3f01-4d1c-9a71-ef7caf9150fa,../../generated/reports-no-bug\11555248-3f01-4...,False,SOLO
3,70c71a91-06a1-4bf4-8e56-f4327b1c8b3f,../../generated/reports-no-bug\70c71a91-06a1-4...,True,SOLO
4,70e85b5e-92d4-498a-9079-ba881f5b3b82,../../generated/reports-no-bug\70e85b5e-92d4-4...,True,TEAM
5,7234f6dc-a316-4576-8453-6e10d7cf1c3d,../../generated/reports-no-bug\7234f6dc-a316-4...,True,SOLO
6,84c2c4e6-1c27-4f2c-808b-9e84a7cb257e,../../generated/reports-no-bug\84c2c4e6-1c27-4...,True,SOLO
7,960ad9f8-2b83-4526-9cfb-1a59cec049a6,../../generated/reports-no-bug\960ad9f8-2b83-4...,False,SOLO
8,bcec21aa-2246-4ee8-9f2a-3998a5cde697,../../generated/reports-no-bug\bcec21aa-2246-4...,True,TEAM
9,c27240eb-52c0-4436-aa0f-e7f97a94a725,../../generated/reports-no-bug\c27240eb-52c0-4...,True,TEAM
10,c27240eb-52c0-4436-aa0f-e7f97a94a725,../../generated/reports-no-bug\c27240eb-52c0-4...,True,SOLO
12,eda1acdb-c4bb-4425-a39f-4c25a998e739,../../generated/reports-no-bug\eda1acdb-c4bb-4...,True,SOLO
13,fb270a09-6a45-4eae-8f9a-3c808faec3ee,../../generated/reports-no-bug\fb270a09-6a45-4...,True,TEAM

# Invalid data

In [3]:
invalid_pitest = main_df[main_df["pitest_valid"] == False]

print(f"Nombre total de projets : {len(main_df)}")
print(f"Nombre de projets valides Pitest :", f"{len(main_df) - len(invalid_pitest)}/{len(main_df)}", f"({(len(main_df) - len(invalid_pitest)) / len(main_df) * 100:.2f}%)")
print(f"Nombre de projets invalides Pitest :", f"{len(invalid_pitest)}/{len(main_df)}", f"({len(invalid_pitest) / len(main_df) * 100:.2f}%)")
print(f"\t Groupe SOLO : {len(invalid_pitest[invalid_pitest['game_mode'] == 'SOLO'])}")
print(f"\t Groupe TEAM : {len(invalid_pitest[invalid_pitest['game_mode'] == 'TEAM'])}")

Nombre total de projets : 13
Nombre de projets valides Pitest : 11/13 (84.62%)
Nombre de projets invalides Pitest : 2/13 (15.38%)
	 Groupe SOLO : 2
	 Groupe TEAM : 0

# User both sessions Pitest valid

In [4]:
cols = ['instruction', 'branch', 'line', 'method']
users_count = len(main_df.groupby('user'))
users_with_valid_pitest = main_df[(main_df['pitest_valid'] == True)]
users = main_df[main_df['user'].isin(users_with_valid_pitest['user'])].copy()

print(f"Nombre d'utilisateurs Pitest valide : {len(users)}/{users_count}")
users

Nombre d'utilisateurs Pitest valide : 11/12

,user,pitest,pitest_valid,game_mode
0,0947a22a-ec40-4f49-867b-330a623a1a35,../../generated/reports-no-bug\0947a22a-ec40-4...,True,TEAM
1,0d271530-be17-4538-bf04-dde3c6069b5f,../../generated/reports-no-bug\0d271530-be17-4...,True,SOLO
3,70c71a91-06a1-4bf4-8e56-f4327b1c8b3f,../../generated/reports-no-bug\70c71a91-06a1-4...,True,SOLO
4,70e85b5e-92d4-498a-9079-ba881f5b3b82,../../generated/reports-no-bug\70e85b5e-92d4-4...,True,TEAM
5,7234f6dc-a316-4576-8453-6e10d7cf1c3d,../../generated/reports-no-bug\7234f6dc-a316-4...,True,SOLO
6,84c2c4e6-1c27-4f2c-808b-9e84a7cb257e,../../generated/reports-no-bug\84c2c4e6-1c27-4...,True,SOLO
8,bcec21aa-2246-4ee8-9f2a-3998a5cde697,../../generated/reports-no-bug\bcec21aa-2246-4...,True,TEAM
9,c27240eb-52c0-4436-aa0f-e7f97a94a725,../../generated/reports-no-bug\c27240eb-52c0-4...,True,TEAM
10,c27240eb-52c0-4436-aa0f-e7f97a94a725,../../generated/reports-no-bug\c27240eb-52c0-4...,True,SOLO
12,eda1acdb-c4bb-4425-a39f-4c25a998e739,../../generated/reports-no-bug\eda1acdb-c4bb-4...,True,SOLO
13,fb270a09-6a45-4eae-8f9a-3c808faec3ee,../../generated/reports-no-bug\fb270a09-6a45-4...,True,TEAM

In [5]:
users_pitest_data = []

for _, user_data in users.iterrows():
    user_pitest_df = pd.read_xml(user_data['pitest']).drop(columns=['indexes', 'blocks', 'killingTests', 'succeedingTests', 'coveringTests'])

    users_pitest_data.append(pd.concat([
        pd.DataFrame({
            'user': user_data['user'],
            'game_mode': user_data['game_mode'],
        }, index=user_pitest_df.index),
        user_pitest_df
    ], axis=1))

pitest_data = pd.concat(users_pitest_data, ignore_index=True)
pitest_data

,user,game_mode,detected,status,numberOfTestsRun,sourceFile,mutatedClass,mutatedMethod,methodDescription,lineNumber,mutator,description
0,0947a22a-ec40-4f49-867b-330a623a1a35,TEAM,False,NO_COVERAGE,0,CombatSystem.java,be.dzenali.gamification.CombatSystem,enemyTurn,()V,133,org.pitest.mutationtest.engine.gregor.mutators...,Replaced integer division with multiplication
1,0947a22a-ec40-4f49-867b-330a623a1a35,TEAM,False,NO_COVERAGE,0,CombatSystem.java,be.dzenali.gamification.CombatSystem,enemyTurn,()V,133,org.pitest.mutationtest.engine.gregor.mutators...,negated conditional
2,0947a22a-ec40-4f49-867b-330a623a1a35,TEAM,False,NO_COVERAGE,0,CombatSystem.java,be.dzenali.gamification.CombatSystem,enemyTurn,()V,135,org.pitest.mutationtest.engine.gregor.mutators...,removed call to be/dzenali/gamification/Combat...
3,0947a22a-ec40-4f49-867b-330a623a1a35,TEAM,False,NO_COVERAGE,0,CombatSystem.java,be.dzenali.gamification.CombatSystem,enemyTurn,()V,136,org.pitest.mutationtest.engine.gregor.mutators...,removed call to be/dzenali/gamification/Combat...
4,0947a22a-ec40-4f49-867b-330a623a1a35,TEAM,False,NO_COVERAGE,0,CombatSystem.java,be.dzenali.gamification.CombatSystem,finishCombat,()V,142,org.pitest.mutationtest.engine.gregor.mutators...,negated conditional
...,...,...,...,...,...,...,...,...,...,...,...,...
3262,fb270a09-6a45-4eae-8f9a-3c808faec3ee,TEAM,False,NO_COVERAGE,0,Item.java,be.dzenali.gamification.item.Item,toString,()Ljava/lang/String;,21,org.pitest.mutationtest.engine.gregor.mutators...,"replaced return value with """" for be/dzenali/g..."
3263,fb270a09-6a45-4eae-8f9a-3c808faec3ee,TEAM,False,NO_COVERAGE,0,CombatLog.java,be.dzenali.gamification.CombatLog,clear,()V,36,org.pitest.mutationtest.engine.gregor.mutators...,removed call to java/util/List::clear
3264,fb270a09-6a45-4eae-8f9a-3c808faec3ee,TEAM,False,NO_COVERAGE,0,CombatLog.java,be.dzenali.gamification.CombatLog,getLogs,()Ljava/util/List;,32,org.pitest.mutationtest.engine.gregor.mutators...,replaced return value with Collections.emptyLi...
3265,fb270a09-6a45-4eae-8f9a-3c808faec3ee,TEAM,False,NO_COVERAGE,0,HealthPotion.java,be.dzenali.gamification.item.consumables.Healt...,toString,()Ljava/lang/String;,20,org.pitest.mutationtest.engine.gregor.mutators...,"replaced return value with """" for be/dzenali/g..."
3266,fb270a09-6a45-4eae-8f9a-3c808faec3ee,TEAM,True,KILLED,6,Aggressivity.java,be.dzenali.gamification.data.Aggressivity,getMultiplier,()D,15,org.pitest.mutationtest.engine.gregor.mutators...,replaced double return with 0.0d for be/dzenal...

In [6]:
df = pitest_data.groupby(['user', 'game_mode', 'sourceFile', 'detected']).size().unstack(fill_value=0)
df.rename(columns={False: 'survived', True: 'killed'}, inplace=True)
df['mutants_count'] = df['survived'] + df['killed']
df.to_csv(f"{code_analysis_generated_path}/pitest-details.csv", index=True)
df

detected                                                           survived  \
user                                 game_mode sourceFile
0947a22a-ec40-4f49-867b-330a623a1a35 TEAM      Aggressivity.java          0
                                               Armor.java                 7
                                               CombatLog.java             2
                                               CombatRules.java           3
                                               CombatSystem.java         40
...                                                                     ...
fb270a09-6a45-4eae-8f9a-3c808faec3ee TEAM      Rogue.java                11
                                               StatBlock.java             7
                                               TradingSystem.java        33
                                               Warrior.java              12
                                               Weapon.java                7

detected                                                           killed  \
user                                 game_mode sourceFile
0947a22a-ec40-4f49-867b-330a623a1a35 TEAM      Aggressivity.java        1
                                               Armor.java               4
                                               CombatLog.java           0
                                               CombatRules.java        21
                                               CombatSystem.java        0
...                                                                   ...
fb270a09-6a45-4eae-8f9a-3c808faec3ee TEAM      Rogue.java               0
                                               StatBlock.java           4
                                               TradingSystem.java       0
                                               Warrior.java             0
                                               Weapon.java              0

detected                                                           mutants_count
user                                 game_mode sourceFile
0947a22a-ec40-4f49-867b-330a623a1a35 TEAM      Aggressivity.java               1
                                               Armor.java                     11
                                               CombatLog.java                  2
                                               CombatRules.java               24
                                               CombatSystem.java              40
...                                                                          ...
fb270a09-6a45-4eae-8f9a-3c808faec3ee TEAM      Rogue.java                     11
                                               StatBlock.java                 11
                                               TradingSystem.java             33
                                               Warrior.java                   12
                                               Weapon.java                     7

[231 rows x 3 columns]

In [8]:
project_data_df = df.groupby(['user', 'game_mode']).sum()
project_data_df['mutation_coverage'] = project_data_df['killed'] / project_data_df['mutants_count']
project_data_df = project_data_df.reset_index()
project_data_df.to_csv(f'{code_analysis_generated_path}/pitest.csv', index=False)
project_data_df

detected,user,game_mode,survived,killed,mutants_count,mutation_coverage
0,0947a22a-ec40-4f49-867b-330a623a1a35,TEAM,155,142,297,0.478114
1,0d271530-be17-4538-bf04-dde3c6069b5f,SOLO,297,0,297,0.000000
2,70c71a91-06a1-4bf4-8e56-f4327b1c8b3f,SOLO,297,0,297,0.000000
3,70e85b5e-92d4-498a-9079-ba881f5b3b82,TEAM,263,34,297,0.114478
4,7234f6dc-a316-4576-8453-6e10d7cf1c3d,SOLO,226,71,297,0.239057
5,84c2c4e6-1c27-4f2c-808b-9e84a7cb257e,SOLO,243,54,297,0.181818
6,bcec21aa-2246-4ee8-9f2a-3998a5cde697,TEAM,297,0,297,0.000000
7,c27240eb-52c0-4436-aa0f-e7f97a94a725,SOLO,237,60,297,0.202020
8,c27240eb-52c0-4436-aa0f-e7f97a94a725,TEAM,237,60,297,0.202020
9,eda1acdb-c4bb-4425-a39f-4c25a998e739,SOLO,267,30,297,0.101010
10,fb270a09-6a45-4eae-8f9a-3c808faec3ee,TEAM,280,17,297,0.057239